server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.6.182:3306/dzy?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=CST&autoReconnect=true
    username: root
    password: 123456 #luna65Ge
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


